#!/usr/bin/python
# -*- coding: UTF-8 -*-

# KVMHOST=qemu+tcp://root@10.252.1.35:16509/system ./virt-host-info

import sys
import datetime
import re
import libvirt
import json
import os
import traceback
from influxdb import InfluxDBClient
from xml.etree import ElementTree

csHost = os.environ["KVM_HOST"]
influxHost = os.environ["INFLUX_HOST"]
influxPort = int(os.environ["INFLUX_PORT"])
influxDB = os.environ["INFLUX_DB"]
influxUser = os.environ["INFLUX_USER"]
influxPassword = os.environ["INFLUX_PASSWORD"]
gatherHostStats = os.environ["GATHER_HOST_STATS"]
debug=os.environ["DEBUG"]

influxClient = InfluxDBClient(influxHost, influxPort, influxUser, influxPassword, influxDB)

try:
	conn = libvirt.open(csHost)
	if conn == None:
		raise Exception("Failed to open connection to %s" % (csHost,))
		exit(1)
	
	
	domainIDs = conn.listDomainsID()
	if domainIDs == None:
		raise Exception('Failed to get a list of domain IDs')
		
	for domainID in domainIDs:
		domain = conn.lookupByID(domainID)
		tree = ElementTree.fromstring(domain.XMLDesc())
		vmHost = {}
		vmHost["host"] = csHost
		vmHost["name"] = domain.name()
		vmHost["uuid"] = domain.UUIDString()
		state, maxmem, mem, cpus, cput = domain.info()
		vmHost["maxmem"] = maxmem
		vmHost["mem"] = mem
		vmHost["cpus"] = cpus
		vmHost["cputime"] = str(cput / 1000000000.)
		vmHost["isrunning"] = domain.isActive()
		vmHost["rss"] = long(domain.memoryStats()["rss"])
		
		vmHost["networkStatistics"] = {}
		netDevs = tree.findall('devices/interface')
		for intf in netDevs:
			dev = intf.find('target').get('dev')
			addr = intf.find('mac').get('address')
			stats = domain.interfaceStats(dev)
			vmHost["networkStatistics"][addr] = {
				"readBytes": 	long(stats[0]),
				"readPackets": 	long(stats[1]),
				"readErrors": 	long(stats[2]),
				"readDrops": 	long(stats[3]),
				"writeBytes": 	long(stats[4]),
				"writePackets": long(stats[5]),
				"writeErrors": 	long(stats[6]),
				"writeDrops": 	long(stats[7])}

		vmHost["diskStatistics"] = {}
		blockDevs = tree.findall('devices/disk')
		for disk in blockDevs:
			if disk.get('device') <> 'disk':
				continue

			dev = disk.find('target').get('dev')
			stats = domain.blockStats(dev)

			source = None
			if disk.get('type') == 'file':
				source = disk.find('source').get('file')
				source = "file://%s" % (source,)
			elif disk.get('type') == 'block':
				source = disk.find('source').get('dev')
				source = "block://%s" % (source,)
			elif disk.get('type') == 'network' and disk.find('source').get('protocol') == 'rbd':
				source = disk.find('source').get('name')
				source = "rbd://%s" % (source,)
			else:
				raise Exception("Undefined or Unknown device type for VM: %s." % (vmHost["name"],))

			if source is not None:
				vmHost["diskStatistics"][source] = {
					"readIOPS" :  long(stats[0]),
					"readBytes":  long(stats[1]),
					"writeIOPS":  long(stats[2]),
					"writeBytes": long(stats[3]),
					"ioErrors":   long(stats[4])}
		
		tags = {
			"vmId": vmHost["name"],
			"vmUuid": vmHost["uuid"],
			"vmHost": vmHost["host"],
		}
		
		query = [
			{
				"measurement": "cpuTime",
				"tags": tags,
				"fields": {
					"cpuTime": float(vmHost["cputime"]),
					"cpus": int(vmHost["cpus"])
				}
			},
			{
				"measurement": "rss",
				"tags": tags,
				"fields": {
					"rss": long(vmHost["rss"]),
					"mem": long(vmHost["mem"]),
					"maxmem": long(vmHost["maxmem"])
				}
			},
		]
		
		for key in vmHost["networkStatistics"].keys():
			netTags = tags.copy()
			netTags["mac"] = key
				
			query.append({
				"measurement": "networkInterface",
				"tags": netTags,
				"fields": vmHost["networkStatistics"][key]
			})
		
		for path in vmHost["diskStatistics"].keys():
			parts = path.split('/')
			diskTags = tags.copy()
			diskTags["image"] = parts[-1]
			diskTags["pool"] = parts[-2]
			query.append({
				"measurement": "disk",
				"tags": diskTags,
				"fields": vmHost["diskStatistics"][path]
			})
		influxClient.write_points(query)
		if debug == 'true':
			print json.dumps(query, sort_keys=True, indent=4, separators=(',', ': '))
			print "\n"

	if gatherHostStats == 'true':
		query = []
		stats = conn.getCPUStats(libvirt.VIR_NODE_CPU_STATS_ALL_CPUS)
		nodeinfo = conn.getInfo()
		mem = conn.getFreeMemory()
		query.append({
			"measurement": "nodeInfo",
			"tags": { 'vmHost': csHost },
			"fields": {
				'kernel': long(stats['kernel']  / 1000000000.),
				'idle': long(stats['idle'] / 1000000000.),
				'user': long(stats['user'] / 1000000000.),
				'iowait': long(stats['iowait'] / 1000000000.),
				'totalMem': nodeinfo[1],
				'freeMem': long(mem / 1024 / 1024)
			}
		})

		influxClient.write_points(query)

		if debug == 'true':
			print json.dumps(query, sort_keys=True, indent=4, separators=(',', ': '))
			print "\n"

		
	conn.close()

except Exception as e:
        traceback.print_exc(file=sys.stderr)
        
